package edu.lewis.cs.adrian.fragmentrating;


public class Rating {

    private int id;
    private String ratingName;
    private int ratingNumber;
    private String ratingReason;

    public Rating(int id, String ratingName, int ratingNumber, String ratingReason) {
        this.id = id;
        this.ratingName = ratingName;
        this.ratingNumber = ratingNumber;
        this.ratingReason = ratingReason;
    }

    public Rating(){

    }

    //  getters and setters //


    public int getId() {
        return id;
    }

    public void setId(int id) {
        this.id = id;
    }

    public String getRatingName() {
        return ratingName;
    }

    public void setRatingName(String ratingName) {
        this.ratingName = ratingName;
    }

    public int getRatingNumber() {
        return ratingNumber;
    }

    public void setRatingNumber(int ratingNumber) {
        this.ratingNumber = ratingNumber;
    }

    public String getRatingReason() {
        return ratingReason;
    }

    public void setRatingReason(String ratingReason) {
        this.ratingReason = ratingReason;
    }

    // toString method generated by ide
    @Override
    public String toString() {
        return "Rating{" +
                "id=" + id +
                ", ratingName='" + ratingName + '\'' +
                ", ratingNumber=" + ratingNumber +
                ", ratingReason='" + ratingReason + '\'' +
                '}';
    }


}//end of class <Rating>



