package edu.lewis.cs.adrian.databaserating;

import androidx.room.Entity;
import androidx.room.Ignore;
import androidx.room.PrimaryKey;

@Entity
public class Rating {

    @PrimaryKey(autoGenerate = true)
    private int id;
    private String ratingName;
    private int ratingNumber;
    private String ratingReason;
    private String ratingWouldYou;
    private int radioButtonId;

    public Rating(String ratingName, int ratingNumber, String ratingReason, int radioButtonId) {

        this.ratingName = ratingName;
        this.ratingNumber = ratingNumber;
        this.ratingReason = ratingReason;
        this.radioButtonId = radioButtonId;
    }

    @Ignore
    public Rating(){

    }

    //  getters and setters //
    public int getId() {
        return id;
    }

    public void setId(int id) {
        this.id = id;
    }

    public String getRatingName() {
        return ratingName;
    }

    public void setRatingName(String ratingName) {
        this.ratingName = ratingName;
    }

    public int getRatingNumber() {
        return ratingNumber;
    }

    public void setRatingNumber(int ratingNumber) {
        this.ratingNumber = ratingNumber;
    }

    public String getRatingReason() {
        return ratingReason;
    }

    public void setRatingReason(String ratingReason) {
        this.ratingReason = ratingReason;
    }

    public String getRatingWouldYou() {
        return ratingWouldYou;
    }

    public void setRatingWouldYou(String ratingWouldYou) {
        this.ratingWouldYou = ratingWouldYou;
    }

    public int getRadioButtonId() {
        return radioButtonId;
    }

    public void setRadioButtonId(int radioButtonId) {
        this.radioButtonId = radioButtonId;
    }

    // toString method generated by ide

    @Override
    public String toString() {
        return "Rating{" +
                "id=" + id +
                ", ratingName='" + ratingName + '\'' +
                ", ratingNumber=" + ratingNumber +
                ", ratingReason='" + ratingReason + '\'' +
                ", ratingWouldYou='" + ratingWouldYou + '\'' +
                '}';
    }
}//end of class



