package edu.lewis.cs.adrian.firebasewebsiterating;


public class WebsiteRating {

    private String ratingName;
    private int ratingNumber;
    private String ratingReason;
    private String ratingWouldYou;
    private int radioButtonId;
    /** todo
     * i could make a int uid variable to just get the user data
     * but i want to show that i have populate the database
     * */


    public WebsiteRating(String ratingName, int ratingNumber, String ratingReason, int radioButtonId) {

        this.ratingName = ratingName;
        this.ratingNumber = ratingNumber;
        this.ratingReason = ratingReason;
        this.radioButtonId = radioButtonId;
    }


    public WebsiteRating(){

    }

    //  getters and setters //

    public String getRatingName() {
        return ratingName;
    }

    public void setRatingName(String ratingName) {
        this.ratingName = ratingName;
    }

    public int getRatingNumber() {
        return ratingNumber;
    }

    public void setRatingNumber(int ratingNumber) {
        this.ratingNumber = ratingNumber;
    }

    public String getRatingReason() {
        return ratingReason;
    }

    public void setRatingReason(String ratingReason) {
        this.ratingReason = ratingReason;
    }

    public String getRatingWouldYou() {
        return ratingWouldYou;
    }

    public void setRatingWouldYou(String ratingWouldYou) {
        this.ratingWouldYou = ratingWouldYou;
    }

    public int getRadioButtonId() {
        return radioButtonId;
    }

    public void setRadioButtonId(int radioButtonId) {
        this.radioButtonId = radioButtonId;
    }

    // toString method generated by ide

    @Override
    public String toString() {
        return "WebsiteRating{" +
                ", ratingName='" + ratingName + '\'' +
                ", ratingNumber=" + ratingNumber +
                ", ratingReason='" + ratingReason + '\'' +
                ", ratingWouldYou='" + ratingWouldYou + '\'' +
                '}';
    }
}//end of class

